gitlab:
    url: http://gitlab.kukewang.com:8082
    user: code-reviewer
    token: ieBoKrVgoXxZNXg6kryr

ai:
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api_key: sk-a850fa52a0984fbbbd45b18b9d864cfe
    model: qwen-coder-turbo
    role_desc: you are a code reviewer
    prompt: 你是一个代码审核者，请 review 代码，找出代码中的问题，给出关键问题的描述，字数在 300 字以内，
    如果是配置类代码片段，请返回空字符串。
